# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - uwrt_arm_controller
    - gripper_controller

  uwrt_arm_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_6