version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "/"
    assignees:
      - "niiquaye"
      - "keyonjerome"
    reviewers:
      - "niiquaye"
      - "keyonjerome"
