sudo: required

language: cpp

services:
  - docker

env:
  global:
    - toolset_branch: master
    - server_type: travis
    - ros_release_name: melodic
    - ubuntu_version_name: bionic
    - used_modules: check_cache,code_style_check,check_build,all_tests,benchmarking,check_install,build_debs,check_deb_make,code_coverage,codecov_tool
    - remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh'

script:
  - curl -s "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" | bash -x /dev/stdin "$toolset_branch" $server_type $used_modules

