<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- TODO(someshdaga): Define the model of the arm accurately
       i.e dimensions, layout, limits, efforts, meshes, materials etc -->

  <!-- Include utility macros for simplying the urdfs -->
	<xacro:include filename="$(find uwrt_arm_description)/urdf/utils/utils.xacro"/>
  <!-- Include macros for arm -->
  <xacro:include filename="$(find uwrt_arm_description)/urdf/arm/arm.gazebo.xacro"/>
  <xacro:include filename="$(find uwrt_arm_description)/urdf/arm/arm.transmission.xacro"/>

  <!-- Link Properties -->
  <xacro:property name="turntable_mass"           value="5"/>    <!-- kg -->
  <xacro:property name="turntable_radius"         value="0.1"/>  <!-- m -->
  <xacro:property name="turntable_height"         value="0.05"/> <!-- m -->

  <xacro:property name="shoulder_revolute_link_mass"   value="1.0"/>   <!-- kg -->
  <xacro:property name="shoulder_revolute_link_height" value="0.05"/>  <!-- m -->
  <xacro:property name="shoulder_revolute_link_length" value="0.286"/> <!-- m -->
  <xacro:property name="shoulder_revolute_link_width"  value="0.10"/>  <!-- m -->

  <xacro:property name="bicep_mass"               value="3.0"/>   <!-- kg -->
  <xacro:property name="bicep_height"             value="0.05"/>  <!-- m -->
  <xacro:property name="bicep_length"             value="0.462"/> <!-- m -->
  <xacro:property name="bicep_width"              value="0.10"/>  <!-- m -->

  <xacro:property name="forearm_mass"             value="3.0"/>   <!-- kg -->
  <xacro:property name="forearm_height"           value="0.05"/>  <!-- m -->
  <xacro:property name="forearm_length"           value="0.356"/> <!-- m -->
  <xacro:property name="forearm_width"            value="0.10"/>  <!-- m -->

  <xacro:property name="claw_mass"                value="0.01"/>   <!-- kg -->
  <xacro:property name="claw_height"              value="0.05"/>  <!-- m -->
  <xacro:property name="claw_length"              value="0.228"/> <!-- m -->
  <xacro:property name="claw_width"               value="0.05"/>  <!-- m -->

  <!-- Joint Properties -->
  <xacro:property name="turntable_min_angle"      value="-120.0"/> <!-- deg -->
  <xacro:property name="turntable_max_angle"      value="120.0"/>  <!-- deg -->
  <xacro:property name="turntable_max_vel"        value="0.5"/>    <!-- rad/s -->
  <xacro:property name="turntable_max_effort"     value="75"/>

  <!-- This values will inform the 'fake' revolute joint, that is modelled 
       to represent an "open" chain version of the closed kinematic chain
       on the real robot -->
  <xacro:property name="shoulder_min_angle"       value="-20.0"/> <!-- deg -->
  <xacro:property name="shoulder_max_angle"       value="75.0"/> <!-- deg -->
  <xacro:property name="shoulder_max_effort"      value="75"/>
  <!-- The max speed specified here should be the worst case scenario
        i.e. over the range of positions the 'fake' revolute joint can assume,
             this maximum speed is the lowest over that range -->
  <xacro:property name="shoulder_max_vel"         value="1.0"/> <!-- rad/s -->
  <!-- The max acceleration specified here should be the worst case scenario
        i.e. over the range of positions the 'fake' revolute joint can assume,
             this maximum acceleration is the lowest over that range -->
  <xacro:property name="shoulder_max_accel"       value="0.1"/> <!-- rad/s^2 -->

  <xacro:property name="elbow_min_angle"          value="0.0"/>  <!-- deg -->
  <xacro:property name="elbow_max_angle"          value="80.0"/> <!-- deg -->
  <xacro:property name="elbow_max_vel"            value="1.0"/>  <!-- rad/s -->
  <xacro:property name="elbow_max_effort"         value="75"/>

  <xacro:property name="wrist_roll_min_angle"     value="-135.0"/> <!-- deg -->
  <xacro:property name="wrist_roll_max_angle"     value="135.0"/>  <!-- deg -->
  <xacro:property name="wrist_roll_max_vel"       value="1.0"/>    <!-- rad/s -->
  <xacro:property name="wrist_roll_max_effort"    value="75"/>

  <xacro:property name="wrist_pitch_min_angle"    value="-75.0"/>  <!-- deg -->
  <xacro:property name="wrist_pitch_max_angle"    value="75.0"/>   <!-- deg -->
  <xacro:property name="wrist_pitch_max_vel"      value="1.0"/>    <!-- rad/s -->
  <xacro:property name="wrist_pitch_max_effort"   value="100"/>

  <!-- Add a small offset distance at the joints between links so they don't collide with 
       each other during motion -->
  <xacro:property name="joint_offset"             value="0.05"/> <!-- m -->

  <xacro:macro name="arm" params="parent name">
    <!-- (JOINT) MOBILE BASE/WORLD -> TURNTABLE -->
    <joint name="${name}_base_turntable_joint" type="revolute">
      <parent link="${parent}"/>
      <child  link="${name}_turntable_link"/>
      <origin xyz="0 0 ${turntable_height / 2}"
              rpy="0 0 0"/>
      <axis   xyz="0 0 1"
              rpy="0 0 0"/> 
      <limit lower="${turntable_min_angle * M_PI / 180.0}"
             upper="${turntable_max_angle * M_PI / 180.0}"
             effort="${turntable_max_effort}"
             velocity="${turntable_max_vel}"/>
    </joint>

    <!-- (LINK) TURNTABLE -->
    <link name="${name}_turntable_link">
      <inertial>
        <mass value="${turntable_mass}"/>
        <origin xyz="0 0 ${turntable_height / 2}" rpy="0 0 0"/>
        <cylinder_inertia_def radius="${turntable_radius}"
                              length="${turntable_height}"
                              mass="${turntable_mass}"/>
      </inertial>

      <visual>
        <origin xyz="0 0 ${turntable_height / 2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${turntable_radius}"
                      length="${turntable_height}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${turntable_height / 2}"
                rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${turntable_radius}"
                      length="${turntable_height}"/>
        </geometry>
      </collision> 
    </link>

    <!-- (JOINT) TURNTABLE -> SHOULDER REVOLUTE LINK -->
    <joint name="${name}_shoulder_joint" type="revolute">
      <parent link="${name}_turntable_link"/>
      <child  link="${name}_shoulder_revolute_link"/>
      <origin xyz="0 0 ${turntable_height/2 + 0.05}"
              rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit lower="${shoulder_min_angle * M_PI / 180.0}"
             upper="${shoulder_max_angle * M_PI / 180.0}"
             effort="${shoulder_max_effort}"
             velocity="${shoulder_max_vel}"/>
    </joint>

    <!-- (LINK) SHOULDER_REVOLUTE_LINK -->
    <link name="${name}_shoulder_revolute_link">
      <inertial>
        <mass value="${shoulder_revolute_link_mass}"/>
        <origin xyz="0 0 ${shoulder_revolute_link_length/2}"
                rpy="0 0 0"/>
        <cuboid_inertia_def width="${shoulder_revolute_link_width}"
                            length="${shoulder_revolute_link_length}"
                            height="${shoulder_revolute_link_height}"
                            mass="${shoulder_revolute_link_mass}"/>
      </inertial>

      <visual>
        <origin xyz="0 0 ${shoulder_revolute_link_length/2}"
                rpy="0 0 0"/>
        <geometry>
          <box size="${shoulder_revolute_link_width}
                     ${shoulder_revolute_link_height}
                     ${shoulder_revolute_link_length}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${shoulder_revolute_link_length/2}"
                rpy="0 0 0"/>
        <geometry>
          <box size="${shoulder_revolute_link_width}
                     ${shoulder_revolute_link_height}
                     ${shoulder_revolute_link_length}"/>
        </geometry>
      </collision>
    </link>

    <!-- (JOINT) SHOULDER->BICEP (NOT ACTUATED) -->
    <joint name="${name}_shoulder_bicep_joint" type="fixed">
      <parent link="${name}_shoulder_revolute_link"/>
      <child  link="${name}_bicep_link"/>
      <origin xyz="0 0 ${shoulder_revolute_link_length}"
              rpy="0 ${(180.0 - 60.3) * M_PI / 180.0} 0"/>
    </joint>

    <!-- (LINK) BICEP -->
    <link name="${name}_bicep_link">
      <inertial>
        <mass value="${bicep_mass}"/>
        <origin xyz="0 0 ${bicep_length/2}"
                rpy="0 0 0"/>
        <cuboid_inertia_def width="${bicep_width}"
                            length="${bicep_length}"
                            height="${bicep_height}"
                            mass="${bicep_mass}"/>
      </inertial>

      <visual>
        <origin xyz="0 0 ${bicep_length/2}"
                rpy="0 0 0"/>
        <geometry>
          <box size="${bicep_width}
                     ${bicep_height}
                     ${bicep_length}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${bicep_length/2}"
                rpy="0 0 0"/>
        <geometry>
          <box size="${bicep_width}
                     ${bicep_height}
                     ${bicep_length}"/>
        </geometry>
      </collision>
    </link>

    <!-- (JOINT) ELBOW (BICEP->FOREARM) -->
    <joint name="${name}_elbow_joint" type="revolute">
      <parent link="${name}_bicep_link"/>
      <child  link="${name}_forearm_link"/>
      <origin xyz="0 0 ${bicep_length}"
              rpy="0 ${-86.58 * M_PI / 180.0} 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${elbow_min_angle * M_PI / 180.0}"
             upper="${elbow_max_angle * M_PI / 180.0}"
             effort="${elbow_max_effort}"
             velocity="${elbow_max_vel}"/>
    </joint>

    <!-- (LINK) FOREARM -->
    <link name="${name}_forearm_link">
      <inertial>
        <mass value="${forearm_mass}"/>
        <origin xyz="0 0 ${forearm_length/2}"
                rpy="0 0 0"/>
        <cuboid_inertia_def width="${forearm_width}"
                            length="${forearm_length}"
                            height="${forearm_height}"
                            mass="${forearm_mass}"/>
      </inertial>

      <visual>
        <origin xyz="0 0 ${forearm_length/2}"
                rpy="0 0 0"/>
        <geometry>
          <box size="${forearm_width}
                     ${forearm_height}
                     ${forearm_length}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${forearm_length/2}"
                rpy="0 0 0"/>
        <geometry>
          <box size="${forearm_width}
                     ${forearm_height}
                     ${forearm_length}"/>
        </geometry>
      </collision>
    </link>

    <!-- (JOINT) WRIST [ROLL] -->
    <joint name="${name}_wrist_roll_joint" type="revolute">
      <parent link="${name}_forearm_link"/>
      <child  link="${name}_wrist_link"/>
      <origin xyz="0 0 ${forearm_length + 0.01}"
              rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${wrist_roll_min_angle * M_PI / 180.0}"
             upper="${wrist_roll_max_angle * M_PI / 180.0}"
             effort="${wrist_roll_max_effort}"
             velocity="${wrist_roll_max_vel}"/>
    </joint>

    <!-- (LINK) FAKE WRIST
         (Virtual link break differential transmission into 2 simple transmissions) -->
    <link name="${name}_wrist_link">
      <inertial>
        <mass value="0.25"/>
        <origin xyz="0 0 0"
                rpy="0 0 0"/>
        <cuboid_inertia_def width="0.05"
                            length="0.01"
                            height="0.05"
                            mass="0.25"/>
      </inertial>

      <visual>
        <origin xyz="0 0 0"
                rpy="0 0 0"/>
        <geometry>
          <box size="0.05
                     0.05
                     0.01"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0"
                rpy="0 0 0"/>
        <geometry>
          <box size="0.05
                     0.05
                     0.01"/>
        </geometry>
      </collision>
    </link>

    <!-- (JOINT) WRIST [PITCH] -->
    <joint name="${name}_wrist_pitch_joint" type="revolute">
      <parent link="${name}_wrist_link"/>
      <child  link="${name}_claw_link"/>
      <origin xyz="0 0 0.01"
              rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="${wrist_pitch_min_angle * M_PI / 180.0}"
             upper="${wrist_pitch_max_angle * M_PI / 180.0}"
             effort="${wrist_pitch_max_effort}"
             velocity="${wrist_pitch_max_vel}"/>
    </joint>

    <!-- (LINK) CLAW -->
    <link name="${name}_claw_link" type="fixed">
      <inertial>
        <mass value="${claw_mass}"/>
        <origin xyz="0 0 ${claw_length / 2}" rpy="0 0 0"/>
        <cuboid_inertia_def width="${claw_width}" length="${claw_length}" height="${claw_height}"
                            mass="${claw_mass}"/>
      </inertial>

      <visual>
        <origin xyz="0 0 ${claw_length / 2}" rpy="0 0 0"/>
        <geometry>
          <box size="${claw_width} ${claw_height} ${claw_length}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${claw_height / 2}" rpy="0 0 0"/>
        <geometry>
          <box size="${claw_width}
                     ${claw_height}
                     ${claw_length}"/>
        </geometry>
      </collision> 
    </link>

    <xacro:arm_gazebo name="${name}"/>
    <xacro:arm_transmission name="${name}"/>

  </xacro:macro>
</robot>
