controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    drivetrain_differential_controller:
      type: diff_drive_controller/DiffDriveController

drivetrain_differential_controller:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_joint, left_middle_wheel_joint, left_rear_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint, right_middle_wheel_joint, right_rear_wheel_joint"]

    wheel_separation: 0.10
    wheels_per_side: 3 
    wheel_radius: 0.015

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x: 
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        max_jerk: 0.0
        min_jerk: 0.0

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
        max_jerk: 0.0
        min_jerk: 0.0
