controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameters:
    joints:
      - right_front_wheel_joint
      - right_middle_wheel_joint
      - right_back_wheel_joint
      - left_front_wheel_joint
      - left_middle_wheel_joint
      - left_nack_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity