chassis:
  length: 1.17
  width: 0.807
  height: 0.2
  mass: 20 #assuming 20kg 

wheels:
  # Should match values defined in uwrt_mars_rover_drivetrain_hw/config/drivetrain_controllers.yaml
  diameter: 0.3
  width: 0.19
  mass: 2.12

control:
  mechanical_reduction: 0.04 # 25:1 reduction
  max_speed: 14.660765716752369 # DB59L048035-A Rated Speed * mechanical_reduction = 3500 / 60 * 2 * pi * 0.04
