chassis:
  length: 1.5
  width: 1.0
  height: 0.15

wheels:
  # Should match values defined in uwrt_mars_rover_drivetrain_hw/config/drivetrain_controllers.yaml
  diameter: 0.3
  width: 0.2
  mass: 0.5

control:
  mechanical_reduction: 0.43
  max_speed: 10
