depth_camera:
  camera1:
    dim:
      length: 0.05
      width: 0.05
      height: 0.05
    parent_link: chassis
    offset:
      x: 0.61
      y: 0
      z: 0

      r_rot: 0
      p_rot: 0
      y_rot: 0
    camera_properties:
      horizontal_fov: 1.047198
      image:
        width: 640
        height: 480
        format: R8G8B8
      clip:
        near: 0.05
        far: 3

  camera2:
    dim:
      length: 0.05
      width: 0.05
      height: 0.05
    parent_link: chassis
    offset:
      x: -0.61
      y: 0
      z: 0

      r_rot: 0
      p_rot: 0
      y_rot: 3.14159265359pi
    camera_properties:
      horizontal_fov: 1.047198
      image:
        width: 640
        height: 480
        format: R8G8B8
      clip:
        near: 0.05
        far: 3

lidar:
  lidar1:
    dim:
      length: 0.05
      width: 0.05
      height: 0.05
    parent_link: chassis
    offset:
      x: 0.4
      y: 0.3
      z: 0.1

      r_rot: 0
      p_rot: 0
      y_rot: 0

    lidar_properties:
      update_rate: 5
      scan:
        samples: 360
        resolution: 1.000000
        min_angle: 0.000000
        max_angle: 6.280000
      range:
        min: 0.120000
        max: 3.5
        resolution: 0.015000
