<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="load_model_data" params="physical_parameters_file">
    <!-- Read .yaml files and load contents into xacro properties -->
    <xacro:property name="physical_parameters" value="${load_yaml(physical_parameters_file)}"/>

    <!--  Extract data from yaml dictionaries  -->
    <xacro:property name="chassis_parameters" value="${physical_parameters['chassis']}"/>
    <xacro:property name="wheel_parameters" value="${physical_parameters['wheels']}"/>

    <xacro:property name="chassis_length" value="${chassis_parameters['length']}" scope="parent"/>
    <xacro:property name="chassis_width" value="${chassis_parameters['width']}" scope="parent"/>
    <xacro:property name="chassis_height" value="${chassis_parameters['height']}" scope="parent"/>

    <xacro:property name="wheel_diameter" value="${wheel_parameters['diameter']}" scope="parent"/>
    <xacro:property name="wheel_width" value="${wheel_parameters['width']}" scope="parent"/>
    <xacro:property name="wheel_mass" value="${wheel_parameters['mass']}" scope="parent"/>
  </xacro:macro>

  <xacro:macro name="default_inertial" params="mass:=5">
    <inertial>
      <mass value="${mass}" />
      <inertia
          ixx="1e-3" ixy="0.0" ixz="0.0"
          iyy="1e-3" iyz="0.0"
          izz="1e-3"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="identical_visual_collision" params="**identical_blocks">
    <visual>
      <xacro:insert_block name="identical_blocks"/>
    </visual>
    <collision>
      <xacro:insert_block name="identical_blocks"/>
    </collision>
  </xacro:macro>

  <xacro:macro name="wheel" params="prefix suffix parent_link reflect wheel_diameter:=^ wheel_width:=^ wheel_mass:=^ wheelbase_length:=^ x_position" >
    <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="${parent_link}"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <origin xyz="${x_position} ${wheelbase_length/2*reflect} 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}_${suffix}_wheel">
      <xacro:identical_visual_collision>
        <idential_blocks>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
          <geometry>
            <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
          </geometry>
        </idential_blocks>
      </xacro:identical_visual_collision>
      <xacro:default_inertial mass="${wheel_mass}"/>
    </link>
  </xacro:macro>

</robot>
