<?xml version="1.0"?>

<robot xmlns:xacro="http://wwww.ros.org/wiki/xacro" name="uwrt_rover_chassis">

<xacro:include filename="$(find uwrt_mars_rover_drivetrain_description)/ros2_control/uwrt_mars_rover_drivetrain.ros2_control.xacro"/>


<!-- 
  wheel_front_left_joint
  wheel_front_right_joint
  wheel_rear_left_joint
  wheel_rear_right_joint
  
-->

<xacro:property name="base_mass" value="1" />
<xacro:property name="base_width" value="0.5" />
<xacro:property name="base_length" value="1" />
<xacro:property name="base_height" value="0.1" />

<!-- Base link -->
<link name="base_link">
  <collision>
      <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
      <geometry>
          <box size="${base_width}  ${base_length} ${base_height}"/>
      </geometry>
  </collision>>

  <visual>
   <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
   <geometry>
          <box size="${base_width}  ${base_length} ${base_height}"/>
   </geometry>
   <material name="blue"/>
  </visual>

  <inertial>
   <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> 
   <mass value="${base_mass}"/>   
   <inertia
    ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
    iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
    izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>      
  </inertial>
</link>

<link name="${side_prefix}_${suffix}_wheel">
  <visual>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder radius="${wheeldiam/2}" length="0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder radius="${wheeldiam/2}" length="0.1"/>
      </geometry>
    </collision>
  <xacro:default_inertial mass="1"/>
  </link>

<joint name="wheel_front_left_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <origin xyz="${baselen*reflect/3} 0 -${wheeldiam/2+.05}" rpy="0 0 0"/>
</joint>




</robot>