   
name: cancel-superceeded-jobs

on: [ push, pull_request ]

jobs:
  cancel-superceded-jobs:
    if: ${{ !github.event.act }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Superceded Jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: ci.yaml
          access_token: ${{ github.token }}